In [79]:
import os
import pandas as pd
import matplotlib as mp

### Best Weights

In [80]:
df = pd.read_csv("best_weights.csv")

df.head
len(df)

6980

In [81]:
queries_data = "/Users/hannahzhang/Desktop/Github Repos/ERSP-TeamYang/data/queries/queries.dev.tsv"

In [82]:
queries_df = pd.read_csv(queries_data, sep="\t", names=['Query Id', 'Query'])

print(queries_df)

        Query Id                            Query
0        1048578   cost of endless pools/swim spa
1        1048579                     what is pcnt
2        1048580                what is pcb waste
3        1048581                    what is pbis?
4        1048582                   what is paysky
...          ...                              ...
101088    480594  price of copper by ounce, pound
101089    524271  trazodone for dogs side effects
101090   1048565    who plays sebastian michaelis
101091   1048570     what is pearls before swine?
101092    524285        treadmill incline meaning

[101093 rows x 2 columns]

### Word/ Character Count

In [83]:
queries = df['Query ID']

char_count_list = []
word_count_list = []

for query in queries:
    query = queries_df.loc[queries_df["Query Id"] == query]["Query"].to_string(index=False).strip()

    char_count = 0
    for char in query:
        if char.isalnum():
            char_count += 1

    word_list = query.split(" ")
    word_count = len(word_list)

    char_count_list.append(char_count)
    word_count_list.append(word_count)


df['Character Count'] = char_count_list 
df['Word Count'] = word_count_list

df.head()

   Query ID  Best Alpha   MRR  Character Count  Word Count
0         2        0.00  1.00               22           3
1   1048585        0.00  0.50               23           5
2    458771        0.00  1.00               26           5
3    163860        0.01  0.25               22           4
4    458774        0.00  0.50               23           4

### Question Type Keywords (what, when, etc...)

In [90]:
what_list = [0] * 6980
where_list = [0] * 6980
when_list = [0] * 6980
why_list = [0] * 6980
how_list = [0] * 6980

queries_subset = queries_df[queries_df["Query Id"].isin(queries)]["Query"]

for idx in range(len(queries_subset)):
    word_list = queries_subset.iloc[idx].lower().split(" ")

    if "what" in word_list:
        what_list[idx] = 1

    if "where" in word_list:
        where_list[idx] = 1

    if "when" in word_list:
        when_list[idx] = 1

    if "why" in word_list:
        why_list[idx] = 1

    if "how" in word_list:
        how_list[idx] = 1

df['What'] = what_list
df['Where'] = where_list
df['When'] = when_list
df['Why'] = why_list
df['How'] = how_list

df

,Query ID,Best Alpha,MRR,Character Count,Word Count,What,Where,When,Why,How
0,2,0.00,1.00,22,3,1,0,0,0,0
1,1048585,0.00,0.50,23,5,0,0,0,0,0
2,458771,0.00,1.00,26,5,0,0,0,0,0
3,163860,0.01,0.25,22,4,1,0,0,0,0
4,458774,0.00,0.50,23,4,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
6975,884722,0.00,1.00,41,7,1,0,0,0,0
6976,393203,0.00,0.20,23,6,0,0,0,0,0
6977,196596,0.01,0.50,26,3,0,1,0,0,0
6978,1048565,0.01,0.20,26,4,1,0,0,0,0
6979,1081338,0.00,1.00,30,6,0,0,0,0,0

In [91]:
questions = queries_df["Query"].to_list()
for question in questions:
    print(question)

cost of endless pools/swim spa
what is pcnt
what is pcb waste
what is pbis?
what is paysky
what is paydata
what is pay range for warehouse specialist in minneapolis
what is paula deen's brother
what is paul gum disease
what is patron
how long is a college hockey game
 Androgen receptor define
treasuries cost basis
treasury officer hong kong average salary
what is patricia cornwell's latest book
what is pastoral medicine
what is past perfect present tense
 definition of Executive Officer defined by FRB
treating diabetes
what is president lincoln known for
what is passage door levers
how long is a cosmic giga second
treating powdery mildew on squash
treating tension headaches without medication
who plays storm in days of future past
how long is a creative writing major
what is pascal's law in simple terms
what is parkland near in florida
what is parkinson, dies
 pneumo is a prefix meaning air. Knowing this, explain why this condition is called pneumothorax
treatment and prognosis for lung cancer
how long is a crew cab silverado
how long is a criminal jury trial
who plays susan warren on snl
 the knee is what type of joint
who plays t bag in prison break
what is parcel service
how long is a cubit?
what is paranoid sc
what is parallel structure? why is it so important in the sermon on the mount?
what is paper with a watermark called
what is pressure vessel testing and repair
what is the gram molecular weight of maltose
treassure island game for ps3 worth
 where are protists most abundant in humans
what is prestonplayz snapchat
treatment for dilated pupils in dogs
what is panama currency called
what is pama liqueur
 you are so dutch means what
how long is a day on planet pluto
what is palm harbor florida
cost of dining in cologne
causes of male urinating blood
what is pain wrapped around my foot
what is page break preview?
what is packaging logistics
what is p-nitroaniline used for
what is p&i paym
price of deodorant and anti
what is oxytocin in a female animal
what is ownership of a corporation called
what is prevail
% saturation do calculation
what is overtures
what is prevailing wage request
'com multi unit' zoning definition
how much is sleep study at hospital
what voltage does a fluorescent light work at
treatment of bubonic plague
cost of credit report from all three credit bureaus
who plays the father in get out movie
) what is the acceleration of the upper block? (indicate the direction with the sign of your answer.)
treatment of copper deficiency
what is overhead rate in managerial accounting?
what is overflow in c++
what is ovalbumin
what is price of pressure treated lumber 2x6x8
who plays the grown up mattie and charlie on young and the restless
who plays the janitor in scrubs
what is outpatient care center
how long is a concealed weapons license good for
treatment of pelvic organ prolapse
who plays the main character in night at the museum
who plays the maytag man
what is outlook data file
how long is a female in heat
treatment of varicose veins in legs
who plays the original john laurens in hamilton broadway
when was the first television broadcast
what is primary and non-contributory under the liability
+how many calories does a person burn in five minutes of standing
how long is a flight feom sfo to floruda
what is outlander
how long is a flight from california to austria
+is biology a social science
what is outer loop
how long is a flight from chicago to australia
average sales salary and commission
treaty of tripoli document
+micheal moore does he wear a wig
what is ott media
what is otp mean on a statement
 guidelines for mothballing of process plants
trebor name meaning
how long is a flight from pittsburgh to las vegas
what is osteo bi flex triple for
what is primary occupancy in fha loans
what is oscopy
cost of concrete cubic yard
cost of concrete apron
what is original parental government issued identification
what is original composition
what is origin of dodge's logo
what is organizing data in database called
cost of combigan generic
+what do pathogic organisms do
how long is a flight from washington dc to manchester nh
+what does ca cells mean urine test
what is primary site of activity of warfarin
what is primary syphilis
+what happen when rome was invaded by germania
+what id justin bieber fav color
what is organic insomnia
who plays trevor in a cowgirls story
tree removal cost deduction
what is prime rate in canada
what is oregon's income tax rate
+what is a lmu wall
how long is a football field in ft
what is oregano oil used to treat?
what is order for installment payments of judgment
what is orange berg on a house
what is oral sexually transmitted diseases
+what is cchaps
+what is centure
what is primidone prescribed for
what county is fairfield ohio in
who plays velma in scooby doo 2
who plays stone in general hospital
tremor in haw
what is oral poetry
what is oracle vpd functionality
cost of clomid for men
what is option button style ?
what is opsonins proteins
what is oprah winfrey's net wo
what is oprah wi
what is opposite of allopathic medicine
what is opportunities in acfta
trend what does it means
who plays what position on st louis cardinals
trending topic meaning
what is opium show las vegas
what is operator in language
who plays xander from bunkd
how long is a good battery life laptop
who plays young dr mallard on ncis
who plays superman in supergirl tv show
what is principal's honor roll
what are the chances of getting a vulpix with drought dexnav
+where is highlong park
trey definition
, does vinegar and water help. remove coffee stains in blouses
triad bladder floor
how long is a hvac class at triton colleg
what is operating system misconfiguration
who prescribes hair loss medications for men
triangle angle sum property definition
how do i install clash of clans on my tablet
how long is a jump rope
. What was the movement called humanism? How did it originate, and what were its main characteristics?
what is priority pass
what is opentable
. difference between isometric & dynamic exercises
who processes rfc
what is prism in eyeglasses
cause of pimples on tip of nose
how long is a ct scan
. what are the president's main duties? explain each
what is a scientist called who observes animals in order to explain their behavior?
. what does the  c prefacing a date mean
who produced peek a boo
. what is the institute for leaders?
who produced stoned love
tribal police department, federal definition
who produced the game centipede
who produced transformers
who produced western aphasia battery
largest mule deer on record
what is web accessibility
how do i insure my step daughters to my auto policy
definition gross wages
what is open application
what is prk lasik
who programs volvo 2006 keys
.net culture code
what is prm?
tricare prime cost 2015
what is op medically
.vbs what it mean
tricare service number
what is onset
what is one way that living organisms use abiotic factors of an ecosystem
who proposed the earth was round?
who proposed the geocentric theory
what is proair hfa
what is one stadia equal
what is probability biology
02 Chevy 1500 Specs
02 how long has my contract left to run
tricks for telling how many lines of symmetry a shape has
tricuspid atresia definition
how much do hostess make at gwinnett medical?
what level does zubat evolves to
who provided the basis for the development of territorial kingdoms?
who provided the first analog key system telephony
trigeminal definition
what is one source of a nonrenewable resource
what is one pound in weight officially
trigeminal neuralgia definition and classification
what is problem solution meaning
how long is a mft valid for
how does muscle tissue regenerate
how to check leave days for the army
who provides electricity for ambit energy?
what is one physical benefit to exercise
what is procedural fluency in math
cost of changing locks for house
how long is a military commitment
what is one main objective in the study of economics?
what is presumptive authority
trigonometric definition math
trikatu empty stomach
what is one example of sociological noise in communication?
what is the maximum allowable interest rate in washington, dc
1 mile equals how many feet
trilobites definition
what is process control equipment
price of front rotors and brakes
how long is a multidose vial good for once opened
how long is a nap ?
what is process improvement (lean six sigma)
1 to 1 1/8 shaft adapter ebay
trintellix metabolism
what is one benefit of social security
what is on the outside of dna
what is omr currency
trip insurance how to cancel
what is ollie ollie oxen
1. define lymph and explain its function
when does daylight saving time return?
treatment for human bites
how long is a normal human gestation period
how long is a day on ven
1/2 cups in tbsp
triptans minimum age
cost of canterbury towers tampa
trismus definition
how long is a paragraph supposed to be
tristesse definition
10 am PST in AST
tritium paint
average weather in wyoming in july
10 factors responsible for depletion of water table
who ran against elected presidents?
who ran against mark sanford
trivex lenses cost
how long is a patent valid in singapore
what is oliver twist ask
treatment for menopause symptoms
what is procure
what is procurement
who ran for the senate against stephen douglas and had a series of debates about slavery with him
what is oklahoma's sales tax rate
trolley line old town address
100g chicken carb content
who read mlk letter from jail
trombone major scale
104 bus time las Vegas
how long is a personal check good for to cash
tron lamborghini
what is oklahoma's absolute location
troon golf courses in hawaii
what is produced during mitosis
how long is a pilot script
who recently fired his caddy this week
11050n autoranging multimeter how to change battery
who recorded a song that was released a hundred years ago
in clia what term replaced quality assurance
why do knees swell up
how long is a powerball ticket valid for
what is oj simpson doing
average schooling and cost for a fashion and merchandising career
calories burned one hour on treadmill
what is product lifecycle
who recorded loving you
treatment for severe blood loss aNemiA
trout in canadian tundra
12.25 mbps upload speed
who recorded silver bullet
how long is a prescription for glasses valid
what is efficacies
troy aikman net worth 2014
120000 jpy to usd
what is product support
what is product validation
who recorded the song still the one?
truck ac dye added for leak check
who recorded uptown funk
how long is a quarter life of a car battery
what is oi meaning english
136 Bus Timetable
who refused the academy award for godfather
what is official mail
14 oct 2015 mlb playoff schedule
what is profanity
who regulates bad faith health insurance complaints
who regulates bail bond companies in california
what is official currency of namibia
what is offered to employees who have been determined to be at risk for exposure to bloodborne pathogens?
what is ocular oncology
14th amendment definition during police
what level is low?
what is ocp in medical
what is oceana organization
what is occult blood lab
what is professional discipline
what is the maximum amount you can get out of an atm
how does my cat feel when i make trouble to him
15 oz can in ml
15 straight line depreciation for leasehold improvements
true manufacturing number of employees
how long is a semester
true meaning of humpty dumpty
what is obstructive bowel syndrome
who released the album drones
who replaced cliff burton in metallica
true that people can die from a broken heart
what is oblique dimension
how do i know if my breasts are done growing
17 nhl stars who fell from grace
how long is a shot of anchor chain
who replaced ted kennedy in the senate
what is objective data collection
who reports hmda data
who represents the president in the budget-making process
what is obama's pension
how long is a specimen good for in formalin
largest official snake ever found
what is nyu ranked
when do the oscar awards start
what is nylon printer ribbon
cost of binghamton university tuition
what is nsr for heart rhythm
how long is a stress test procedure
what is nrg stadium in atl
) what other tissue(s) might harbor streptococcus pyogenes? coursehero
what is nratv
how long is a tax lien allowed to stay on your credit file
how long is a dog's gestation
what is npv used for houston chronicle
cost of bar for basement
trump supporters will write his name in the gop ballot if he does not go third party
what is not present when fermentation is used
trump tower price
what is programs folder
how long is a term in congress?
who s sherlock holmes
cost of bag of apples
who said ''he would fight no more'' and died from heart break
how long is a theft charge
1989 Corvette Blue Book Prices
what is not a secondary challenge of poverty?
what is progressive tax
who said a hero expects a nation to do its duty
1993 penthouse mark whalberg net worth
1995 silver eagle value
1996 yamaha vmax 600 specs
1999 chevy suburban k2500 7.4l what to look for when buying
______ are the spaces between nodes.
who said add insult to injury
exhaustion weighed down limbs
what is project charter in project management
1st trust deed definition
1x8 block with a sticker grand prix what set does it belong
how long is a typical car loan?
truth functional operator and definition
who said by nurturing the artist the community will be enriched
who said character is tested when you're up against it
truth is presented to mind indirectly augustine
2 liters is how many ounces
mount carmel health system employee numbers
2 teaspoons equals how many tablespoons
2 year olds knee hurts when he is sick
how long is a us senator term
2,000,000 Swiss francs in GBP
how long is a valid california driver's license
what is project startup
how long is a voe valid
how long is a washington drivers license good for
what is nosta
what is nortriptyline prescribed for
what is north korea's geography
what is normal size of meatus
20 oz Post raisin bran price
what is normal rea
who said i am a product of my environment
2000 volkswagon cabriolet gas mileage and teliability
who said i have met the enemy and it is us
what is normal range for waist to hip ratio
who said i learned more from my failures than my success edison
tsa wages and benefits
2001vw 1.9 pump timing specs
2002 audi quattro gas mileage
what is normal range for endometrial lining thickness after menopause
who said if you can't buy it twice you can't afford it
how long is a year in earth days on venus
how much do i need to pay in the parking zone of Amsterdam ArenA football stadium
how do i know my cif number in sbi through bank account
tsh level ranges for pregnancy
2005 difference between camry and lexus
how long is a zip code
2006 GMC Yukon XL engine is off, but heater blower is still on
how do i know my lcd is out on my note
what is the maximum dosage of acetaminophen
tsp how long do fund have to be in account before withdrawal?
tsp loan repayment
what is promethazine used for?
tsp retirement age requirements
how long is air force basic
in excel how to remove a space between numbers
how long is air force enlisted intelligence school
tsu rn to bsn online program
2007 va disability compensation rates
tsun meaning
2008 subaru feraster washer moter how to install
who said past behavior predicts future
average salary vice president of real estate
who said sheer presence is the greatest gift
2014 lexus is 250 price
2014 rzr 1000 weight
who said take only pictures, leave only footprints
who said that everyone must participate for democracy to work
2015 Federal Bank Holidays
how long is an amex authorization good for
tudor grange solihull term dates
how long is an appraisal good
2015 average gas price in Nevada
tufts health plan number
2015 blue jays best players
what is proper way to use a surge protector
tuition and fees and colorado technical university
2015 college half term holiday dates
who said the quote its better to have it and not need it than to need it and not have it
2015 federal tax refund schedule
tuition assistance usmc website
most selective colleges in hawaii
tuition cost at greenbrier academy boarding school
tuition cost at wcccd
what is normal range for blood sugars
what is normal psi for male pos
treatment thyroid goiter w/ tracheal deviation
what is normal psa for prostate in m
tuition cost for ole miss
2015 tax rates trust income
what is normal monocytes percent
what is propolis extract
how long is an fha case number good for
how long is an iceland day
how much do i put on an oyster card
how long is an illinois tax lien good for
what is propranolol prescribed for
2015-16 winter weather forecast
what is normal heart rate resting
who said you miss every shot that you don't take.
what is normal fever in cat
how long is an lsat score valid
what is normal expiration for sildenafil
tuition cost when for student when parent is employed at college central michigan university
how long is an nba game
how long is an nfl game time
what is propulsion
cost of installing a solar thermal system in canada
what is normal delivery time for mail
tuition deduction for non-dependent child
average serving of pulled pork per person
what is propylene kit
2016 monster jam lineup
how long is ankle swollen after twist
what was Hillary Clintons response when asked about her accomplishments as Secretary of State
2016 outlook how to save view as default
who sang 'convoy'
what is normal blood su
what is pros cons
who sang Lead me On top gun soundtrack
2016 wonderlic test, nfl
average settlement for hearing damage and loss
2017 college football semi finals schedule
who sang all the man i need first
who sang all these years
what is normal aic
cost of attendance sipa columbia
what is noom?
cost of attendance oregon state colleges
how long is average time to be induced
21 jump street cast
21/2 percent of 4200
what are the characteristics of the eucalyptus
what is non-cirrhotic portal
what is prosoft
tuition waiver @ university of florida
who sang baby i'm amazed by you
how long is baked ham shelf stable
what is non alphanumeric mean
24 Hour eBay Phone Number
24 carat gold price
what county is renton washington in
tulsa university price per credit hour
what is prostate removal
tum mile love reprise lyrics english
who sang boogie nights
250g of chicken is how much protein
25Kg BAG how much area will cover
tumor definition biology
27000 annual salary per hour
what is protected cell company
tumor profiling allele frequency somatic vs germline
what is nokia in spanish
what is noform
how long is buttermilk safe to use
tums ingredients
tumuli definition
what is nocturnal myoclonus
what is noc nokia
how long is canned food safe
most popular youtube categories
what is noble rot
3 characteristics of protozoa replication
cost of attendance eastern illinois university
turbofan definition
how does nba player get paid
why do lipomas grow back
what is nkg
what is njstart
what is niosh approved
what is nike rally
how long is chicken good in the freezer
how long is chicken good in the freezer?
turbo takeoff how much weight do you lose
what is night vision autogate
3 other systems that work with the respiratory system
who sang evil woman
what is nids in it
how long is cicada season
what is primary leg in plexus
turkey and china time difference
turkey bacon ranch wrap calories
turkey broth health benefits
what is nicotine salt
what is nick hagen most famous for
3 types of minerals in food
hip moves
3 ways a log can move when bucking on side hill
turkey passport requirements for non citizens
what is proton gas
how long is a flight from sfo to germany
3 year aggregate definition
how long is computer engineering school
cost of assisted living in colorado springs
3. how might a nitrogen-oxygen atmosphere on the moon affect the range of temperatures on the moon
what is protoplasm
what is new adult romance
3/5 of 60
3/8 inch shank converted to mm
best wr in nfl history

### Question Type

In [96]:
from transformers import BertTokenizer, BertForSequenceClassification
import torch

question_type = []

# Load model
model_name = "PrimeQA/tydiqa-boolean-question-classifier"
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name)

for idx in range(len(queries_subset)):
    question = queries_subset.iloc[idx]

    # Tokenize input question
    inputs = tokenizer(question, return_tensors="pt", truncation=True, padding=True, max_length=512)

    # Get model's output
    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits

    # Convert logits to probabilities using softmax
    probabilities = torch.nn.functional.softmax(logits, dim=-1)

    # Get the predicted class
    predicted_class = torch.argmax(probabilities, dim=-1).item()
    question_type.append(predicted_class)

In [101]:
df["Question Type"] = question_type
df

,Query ID,Best Alpha,MRR,Character Count,Word Count,What,Where,When,Why,How,Question Type
0,2,0.00,1.00,22,3,1,0,0,0,0,0
1,1048585,0.00,0.50,23,5,0,0,0,0,0,1
2,458771,0.00,1.00,26,5,0,0,0,0,0,1
3,163860,0.01,0.25,22,4,1,0,0,0,0,0
4,458774,0.00,0.50,23,4,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
6975,884722,0.00,1.00,41,7,1,0,0,0,0,0
6976,393203,0.00,0.20,23,6,0,0,0,0,0,0
6977,196596,0.01,0.50,26,3,0,1,0,0,0,0
6978,1048565,0.01,0.20,26,4,1,0,0,0,0,0
6979,1081338,0.00,1.00,30,6,0,0,0,0,0,0

### KNN

In [22]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error, r2_score

# Separate data into features and target
X = df.drop(['Best Alpha', 'Query ID'], axis=1)
y = df['Best Alpha']

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Scale features using StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize model
knn = KNeighborsRegressor(n_neighbors=3)

# Fit the model
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

Mean Squared Error: 0.0011154489016236865
R-squared: -0.3067147529610308