## Best Weights

- Goal: Manual Search
    1. Initialize range for alpha (0 to 1)
    2. Combine sparse and dense scores for each combination of alpha (dense) and 1 - alpha (sparse)
    3. Use evaluation metric (MRR) to find best combination of weights

- Evaluation metric: NDCG (Normalized Discounted Cumulative Gain)
    - Prioritizes top-ranked documents by penalizing rankings that place relevant documents lower down in the ranking list

Questions:

- for both splade and bm25, since qrels only provides us with 1 confirmed relevant document, should we use mrr to as an evaluation metric since it only looks at the first relevant document?
    - use mrr

- how to handle weighting when one model ranks a document that the other does not rank at all? 
    - the second model gives it a zero

In [189]:
import numpy as np
import pandas as pd
from sklearn.metrics import ndcg_score
import os
from sklearn.preprocessing import MinMaxScaler

Load Data

In [190]:
data_dir = "/Users/hannahzhang/Desktop/Github Repos/ERSP-TeamYang/data/"

data = []

for file in os.listdir(data_dir):
    if file.endswith(".tsv") or file.endswith(".trec"):
        data.append(data_dir + file)

print(data)

['/Users/hannahzhang/Desktop/Github Repos/ERSP-TeamYang/data/bm25-t5-dev.trec', '/Users/hannahzhang/Desktop/Github Repos/ERSP-TeamYang/data/splade_llama_rerank.tsv', '/Users/hannahzhang/Desktop/Github Repos/ERSP-TeamYang/data/qrels.dev.tsv', '/Users/hannahzhang/Desktop/Github Repos/ERSP-TeamYang/data/splade-dev.trec', '/Users/hannahzhang/Desktop/Github Repos/ERSP-TeamYang/data/collection.tsv', '/Users/hannahzhang/Desktop/Github Repos/ERSP-TeamYang/data/repllama_msmarco_dev.trec']

Splade dataframe

In [191]:
splade_df = pd.read_csv(data[3], sep="\t", names=['Query ID', 'Q0', 'Document ID', 'Rank', 'Score', 'R0'])
splade_df = splade_df.drop(splade_df.columns[[1,5]], axis=1)
# print(splade_df.head)

splade_df['Score'] = splade_df.groupby('Query ID')['Score'].transform(lambda x: MinMaxScaler().fit_transform(x.values.reshape(-1, 1)).flatten())

In [192]:
dense_df = pd.read_csv(data[1], sep="\t", names=['Query ID', 'Document ID', 'Score'])
# print(dense_df.head)

In [193]:
dense_df = pd.read_csv(data[5], sep=" ", names=['Query ID', 'Q0', 'Document ID', 'Null', 'Score', 'Dense'])
dense_df.drop(columns=['Q0', "Null", "Dense"])

         Query ID  Document ID     Score
0         1048585      7187157  0.866932
1         1048585      7187158  0.863535
2         1048585      7187155  0.861530
3         1048585      7187160  0.858853
4         1048585      7187163  0.840336
...           ...          ...       ...
6979995   1048565      4057989  0.791225
6979996   1048565      5112060  0.791218
6979997   1048565      2754970  0.791218
6979998   1048565      1086355  0.791201
6979999   1048565      7285226  0.791189

[6980000 rows x 3 columns]

In [194]:
dense_df['Score'] = dense_df.groupby('Query ID')['Score'].transform(lambda x: MinMaxScaler().fit_transform(x.values.reshape(-1, 1)).flatten())

In [195]:
qrels_df = pd.read_csv(data[2], sep="\t", names=['Query ID', '0', 'Document ID', "Relevance"])
qrels_df = qrels_df.drop(columns=['0'])

qrels_df

# qrels_df.head

       Query ID  Document ID  Relevance
0       1102432      2026790          1
1       1102431      7066866          1
2       1102431      7066867          1
3       1090282      7066900          1
4         39449      7066905          1
...         ...          ...        ...
59268    150337      8009410          1
59269     22241      8009429          1
59270    129177      8009442          1
59271    190655      3576091          1
59272    371455      8009476          1

[59273 rows x 3 columns]

In [196]:
dense_query_ids = []
sparse_query_ids = []


for x in dense_df['Query ID'].unique():
    dense_query_ids.append(int(x))

for x in splade_df['Query ID'].unique():
    sparse_query_ids.append(int(x))

query_ids = list(set(dense_query_ids) & set(sparse_query_ids))

print(len(query_ids))

6980

In [197]:
alpha_values = np.arange(0, 1.01, 0.01)
# print(alpha_values)

In [213]:
def best_weights(dense_df, sparse_df, query_id, alpha_values, qrels_df):
    best_alpha = 0
    best_mrr = 0

    # Filter by query ID
    filtered_dense_df = dense_df[dense_df["Query ID"] == query_id].copy()
    filtered_sparse_df = sparse_df[sparse_df["Query ID"] == query_id].copy()

    for alpha in alpha_values:

        # Find weighted scores
        filtered_dense_df["Score"] *= (1 - alpha)
        filtered_sparse_df["Score"] *= alpha

        # Merge rankings
        merged = filtered_dense_df.merge(filtered_sparse_df, on="Document ID", how="outer", suffixes=("_dense", "_sparse")).fillna(0)
        merged["Final Score"] = merged["Score_dense"] + merged["Score_sparse"]

        # Rank documents
        ranked_results = merged.sort_values("Final Score", ascending=False)
        ranked_docs = ranked_results["Document ID"].tolist()

        # MRR
        relevant_doc = qrels_df[qrels_df["Query ID"] == query_id]["Document ID"].iloc[0]
        if relevant_doc not in ranked_docs:
            mrr_score = 0
        else:
            rank = ranked_docs.index(relevant_doc) + 1
            mrr_score = 1 / rank

        # Update alpha and MRR
        if mrr_score > best_mrr:
            best_mrr = mrr_score
            best_alpha = alpha

    return best_alpha, best_mrr

In [214]:
best_weights(dense_df, splade_df, 2, alpha_values, qrels_df)

(0.0, 1.0)

## Improved Best Weights Function

In [219]:
def best_weights(dense_df, sparse_df, query_id, alpha_values, qrels_df):
    best_alpha = 0
    best_mrr = 0
    no_best_alpha = True

    # Filter by query ID
    filtered_dense_df = dense_df[dense_df["Query ID"] == query_id].copy()
    filtered_sparse_df = sparse_df[sparse_df["Query ID"] == query_id].copy()

    for alpha in alpha_values:

        # Find weighted scores
        weighted_score = (1 - alpha) * filtered_dense_df["Score"].values + alpha * filtered_sparse_df["Score"].values

        # Calculate weighted score
        # merged = pd.concat([filtered_dense_df.reset_index()["Document ID"], pd.DataFrame(weighted_score, columns=["Final Score"])], axis=1)

        merged = pd.DataFrame({
            "Document ID": filtered_dense_df["Document ID"].values,
            "Final Score": weighted_score
        })

        # Rank documents
        ranked_results = merged.sort_values("Final Score", ascending=False)
        ranked_docs = ranked_results["Document ID"].tolist()

        # MRR
        relevant_doc = qrels_df[qrels_df["Query ID"] == query_id]["Document ID"].iloc[0]
        if relevant_doc not in ranked_docs:
            mrr_score = 0
        else:
            rank = ranked_docs.index(relevant_doc) + 1
            mrr_score = 1 / rank
            no_best_alpha = False

        # Update alpha and MRR
        if mrr_score > best_mrr:
            best_mrr = mrr_score
            best_alpha = alpha

    if no_best_alpha:
        return None, None
    
    return best_alpha, best_mrr

In [220]:
# test query
best_weights(dense_df, splade_df, 2, alpha_values, qrels_df)

(0.0, 1.0)

In [221]:
best_alphas = []
best_mrrs = []

for query in query_ids:
    best_alpha, best_mrr = best_weights(dense_df, splade_df, query, alpha_values, qrels_df)
    # print(f"Query ID: {query}, 'Best Alpha': {best_alpha}, 'MRR': {best_mrr}")
    best_alphas.append(best_alpha)
    best_mrrs.append(best_mrr)

best_weights = {'Query ID': query_ids, 'Best Alpha': best_alphas, 'MRR': best_mrrs}

In [230]:
best_mrrs_no_none = [x for x in best_mrrs if x != None]

print(sum(best_mrrs_no_none) / len(best_mrrs))

0.4126590478079081

In [223]:
from collections import Counter

alpha_count = Counter(best_alphas)

for alpha in alpha_count:
    print(alpha, alpha_count[alpha])

0.0 6931
None 46
0.01 1
1.0 2

In [ ]:
import csv

with open("best_weights.csv", "w") as outfile:
	writer = csv.writer(outfile)
	
	# convert dict keys to a list
	key_list = list(best_weights.keys())
	
	writer.writerow(best_weights.keys())
	
	# iterate each column and assign corresponding values to each column
	for i in range(6980):
		writer.writerow([best_weights[x][i] for x in key_list])

In [ ]:
best_weights_df = pd.read_csv("best_weights.csv")

best_weights_df.head